name: "json_schema_plus"
version: "2.0.2+10"
description: "Provide support for validating instances against json schema"
homepage: "https://github.com/peiffer-innovations/json_schema2"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: "^2.3.1"
  collection: "^1.16.0"
  logging: "^1.0.2"
  meta: "^1.7.0"
  path: "^1.8.0"
  rest_client: "^2.1.4+7"
  uri: "^1.0.0"
  yaon: "^1.0.1+3"

dev_dependencies:
  test: "^1.21.4"

ignore_updates:
  - "async"
  - "boolean_selector"
  - "characters"
  - "charcode"
  - "collection"
  - "clock"
  - "fake_async"
  - "file"
  - "matcher"
  - "material_color_utilities"
  - "meta"
  - "path"
  - "source_span"
  - "stack_trace"
  - "stream_channel"
  - "string_scanner"
  - "term_glyph"
  - "vector_math"
